apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: hello-world:latest
              name: hello-container
          restartPolicy: OnFailure
  schedule: "* */1 * * *" #every minute
