apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: postgres:latest
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready --host $POD_IP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
          name: postgres-container
          ports:
            - containerPort: 5432
              name: postgres-port
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready --host $POD_IP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
