---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: flask-hello-world-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/flask-hello-world
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-hello-world-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: flask-hello-world-pod
spec:
  containers:
    - image: ferraroluc/flask-hello-world:latest
      name: flask-hello-world-container
      ports:
        - containerPort: 5000
      volumeMounts:
        - mountPath: /data
          name: flask-hello-world-volume
  volumes:
    - name: flask-hello-world-volume
      persistentVolumeClaim:
        claimName: flask-hello-world-pvc
