apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
        - name: hello-container
          image: hello-world:latest
      restartPolicy: Never
