apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  template:
    spec:
      containers:
        - image: hello-world:latest
          name: hello-container
      restartPolicy: Never
