apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
spec:
  schedule: "* */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nginx-container
              image: nginx:latest
          restartPolicy: OnFailure
