---
apiVersion: v1
data:
  message: SGVsbG8gCg==
kind: Secret
metadata:
  name: envs-secret
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: envs-pod
spec:
  containers:
    - env:
        - name: EXAMPLE
          valueFrom:
            secretKeyRef:
              key: message
              name: envs-secret
      image: ferraroluc/envs:latest
      name: envs-container
